item_profile_order = [
    'Item ID',
    'Status',
    'Catalogue Number',
    'Item Name',
    'Period',
    'Condition',
    'Pricing',
    'Sold Price',
    'newline',
    'Rareness',
    'Short Highlight',
    'Collection Class',
    'newline',
    'Manufacturer',
    'Artist',
    'Series',
    'Model Start Year',
    'Model End Year',
    'Age Class',
    'Height',
    'Length',
    'Width',
    'Market Average',
    'Creation Date',
    'Status Date',
    'newline',
    'Provenance',
    'Item Cost',
    'Additional Cost',
    'Total Cost',
]