item_profile_order = [
    'Item ID',
    'Status',
    'Status Date',
    'Catalogue Number',
    'Item Name',
    'Pricing',
    'Sold Price',
    'newline',
    'Artist',
    'Manufacturer',
    'Series',
    'Model Start Year',
    'Model End Year',
    'Period',
    'Age Class',
    'Height',
    'Length',
    'Width',
    'newline',
    'Market Average',
    'Rareness',
    'Condition',
    'Short Highlight',
    'Collection Class',
    'newline',
    'Item Cost',
    'Additional Cost',
    'Total Cost',
    'Creation Date',
]